/* automatically generated by rust-bindgen */

extern "C" {
    pub fn SDL_imageFilterMMXdetect() -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMMXoff();
}
extern "C" {
    pub fn SDL_imageFilterMMXon();
}
extern "C" {
    pub fn SDL_imageFilterAdd(
        Src1: *mut core::ffi::c_uchar,
        Src2: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMean(
        Src1: *mut core::ffi::c_uchar,
        Src2: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterSub(
        Src1: *mut core::ffi::c_uchar,
        Src2: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterAbsDiff(
        Src1: *mut core::ffi::c_uchar,
        Src2: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMult(
        Src1: *mut core::ffi::c_uchar,
        Src2: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMultNor(
        Src1: *mut core::ffi::c_uchar,
        Src2: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMultDivby2(
        Src1: *mut core::ffi::c_uchar,
        Src2: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMultDivby4(
        Src1: *mut core::ffi::c_uchar,
        Src2: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterBitAnd(
        Src1: *mut core::ffi::c_uchar,
        Src2: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterBitOr(
        Src1: *mut core::ffi::c_uchar,
        Src2: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterDiv(
        Src1: *mut core::ffi::c_uchar,
        Src2: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterBitNegation(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterAddByte(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        C: core::ffi::c_uchar,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterAddUint(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        C: core::ffi::c_uint,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterAddByteToHalf(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        C: core::ffi::c_uchar,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterSubByte(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        C: core::ffi::c_uchar,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterSubUint(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        C: core::ffi::c_uint,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftRight(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        N: core::ffi::c_uchar,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftRightUint(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        N: core::ffi::c_uchar,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterMultByByte(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        C: core::ffi::c_uchar,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftRightAndMultByByte(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        N: core::ffi::c_uchar,
        C: core::ffi::c_uchar,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftLeftByte(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        N: core::ffi::c_uchar,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftLeftUint(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        N: core::ffi::c_uchar,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterShiftLeft(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        N: core::ffi::c_uchar,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterBinarizeUsingThreshold(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        T: core::ffi::c_uchar,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterClipToRange(
        Src1: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        Tmin: core::ffi::c_uchar,
        Tmax: core::ffi::c_uchar,
    ) -> core::ffi::c_int;
}
extern "C" {
    pub fn SDL_imageFilterNormalizeLinear(
        Src: *mut core::ffi::c_uchar,
        Dest: *mut core::ffi::c_uchar,
        length: core::ffi::c_uint,
        Cmin: core::ffi::c_int,
        Cmax: core::ffi::c_int,
        Nmin: core::ffi::c_int,
        Nmax: core::ffi::c_int,
    ) -> core::ffi::c_int;
}
