/* automatically generated by rust-bindgen */

use crate::*;

pub type __uint8_t = core::ffi::c_uchar;
pub type __uint32_t = core::ffi::c_uint;
pub type Uint8 = u8;
pub type Uint32 = u32;
extern "C" {
    pub fn rotozoomSurface(
        src: *mut SDL_Surface,
        angle: f64,
        zoom: f64,
        smooth: core::ffi::c_int,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn rotozoomSurfaceXY(
        src: *mut SDL_Surface,
        angle: f64,
        zoomx: f64,
        zoomy: f64,
        smooth: core::ffi::c_int,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn rotozoomSurfaceSize(
        width: core::ffi::c_int,
        height: core::ffi::c_int,
        angle: f64,
        zoom: f64,
        dstwidth: *mut core::ffi::c_int,
        dstheight: *mut core::ffi::c_int,
    );
}
extern "C" {
    pub fn rotozoomSurfaceSizeXY(
        width: core::ffi::c_int,
        height: core::ffi::c_int,
        angle: f64,
        zoomx: f64,
        zoomy: f64,
        dstwidth: *mut core::ffi::c_int,
        dstheight: *mut core::ffi::c_int,
    );
}
extern "C" {
    pub fn zoomSurface(
        src: *mut SDL_Surface,
        zoomx: f64,
        zoomy: f64,
        smooth: core::ffi::c_int,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn zoomSurfaceSize(
        width: core::ffi::c_int,
        height: core::ffi::c_int,
        zoomx: f64,
        zoomy: f64,
        dstwidth: *mut core::ffi::c_int,
        dstheight: *mut core::ffi::c_int,
    );
}
extern "C" {
    pub fn shrinkSurface(
        src: *mut SDL_Surface,
        factorx: core::ffi::c_int,
        factory: core::ffi::c_int,
    ) -> *mut SDL_Surface;
}
extern "C" {
    pub fn rotateSurface90Degrees(
        src: *mut SDL_Surface,
        numClockwiseTurns: core::ffi::c_int,
    ) -> *mut SDL_Surface;
}
